/*
* WARNING: This migration file was auto-generated by @anclatechs/sql-buns-migrate
* on November 22, 2025 (version 1.0.0).
*
* Do not edit this file manually, as it may complicate the migration process
* or lead to unexpected issues. If changes are needed, regenerate the file
* or modify the source configuration instead. Only proceed with direct edits
* if you are absolutely certain of the implications.
*/
import { pool } from "@anclatechs/sql-buns";
export async function up() {/**Go to file: 1763852390341_0000_initial_inspectdb.sql*/}
export async function down() {
  await pool.run(`DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS _sqlbuns_migrations;
DROP TABLE IF EXISTS user_level_history;`);
}