/*
 * WARNING: This migration file was auto-generated by @anclatechs/sql-buns-migrate
 * on October 28, 2025 (version 1.0.0).
 *
 * Do not edit this file manually, as it may complicate the migration process
 * or lead to unexpected issues. If changes are needed, regenerate the file
 * or modify the source configuration instead. Only proceed with direct edits
 * if you are absolutely certain of the implications.
 */
import { pool } from "@anclatechs/sql-buns";
export async function up() {/**See 1761648341756_new.sql*/}
export async function down() {
  await pool.run(`DROP TABLE IF EXISTS users;
DROP INDEX IF EXISTS idx_users_email
DROP TRIGGER IF EXISTS trg_users_insert_after_0 ON users;
DROP TRIGGER IF EXISTS trg_users_update_after_0 ON users;
DROP TRIGGER IF EXISTS trg_users_insert_after_1 ON users;
DROP TRIGGER IF EXISTS trg_users_update_after_1 ON users;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS user_level_history;`);
}
  